### ISSUE TITLE
Cannot set Node version

### ISSUE THREAD

**Issue by rkdefra** [DEFRA/ado-pipeline-common#155]
https://github.com/DEFRA/ado-pipeline-common/blob/e7137f6c0a8a4d8714bc0c9c4127a2ba5ab4aac1/docs/AppBuildAndDeploy.md?plain=1#L312

The following yaml is from our `.azuredevops/build.yaml` file, and seems to make no difference to the Node version used for the testing step (or other Node steps)
```yaml
extends:
  template: /pipelines/common-app-build.yaml@DEFRA-ADPPipelineCommon
  parameters:
    teamName: "fcp-dal"
    serviceName: "fcp-data-access-layer-api"
    deployFromFeature: ${{ parameters.deployFromFeature }}
    deployConfigOnly: ${{ parameters.deployConfigOnly }}
    appBuildConfig:
      appFrameworkType: "nodejs"
      frameworkVersion: "22.x"
```
I would expect the `frameworkVersion: "22.x"` config to set the target version for the steps, but no joy. Also tried other version styles: `22.13.1`, `v22`, and `v22.13.1`.
